service: SkLambda-tree

plugins:
  - serverless-python-requirements

provider:
  name: aws
  region: us-east-1
  runtime: python3.7
  stage: dev

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - ${self:provider.environment.BUCKET}
           - "/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

  environment:
    BUCKET: serverless-ml-1

functions:
  upload:
    handler: upload.uploadHandler
    layers:
      - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-numpy:10
      - arn:aws:lambda:us-east-1:446751924810:layer:python-3-7-scikit-learn-0-23-1:2
    timeout: 30
    events:
      - http:
          path: upload
          method: post

  train:
    handler: train.trainHandler
    layers:
      - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-numpy:10
      - arn:aws:lambda:us-east-1:446751924810:layer:python-3-7-scikit-learn-0-23-1:2
    memorySize: 3008
    timeout: 30
    events:
      - http:
          path: train
          method: post

  infer:
    handler: infer.inferHandler
    layers:
      - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-numpy:10
      - arn:aws:lambda:us-east-1:446751924810:layer:python-3-7-scikit-learn-0-23-1:2
    memorySize: 3008
    timeout: 30
    events:
      - http:
          path: infer
          method: post

  inferqueue:
    handler: inferqueue.inferqueueHandler
    layers:
      - arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-numpy:10
      - arn:aws:lambda:us-east-1:446751924810:layer:python-3-7-scikit-learn-0-23-1:2
    memorySize: 3008
    timeout: 900
    events:
      - http:
          path: inferqueue
          method: post


custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    noDeploy:
      - boto3
      - botocore
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - s3transfer
      - setuptools
      - six
      - tensorboard

resources:
  Resources:
    SageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
